name: CI/CD Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build app
        run: echo "Building..."
      - name: Test
        run: echo "Running unit tests..."
      - name: Deploy
        run: echo "Deploying to staging..."

